# Generated by Django 5.0.6 on 2024-07-03 15:35

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gasoline_tanks', models.IntegerField()),
                ('gas_tanks', models.IntegerField()),
                ('gasoline_nozzles', models.IntegerField()),
                ('gas_nozzles', models.IntegerField()),
                ('gasoline_beginning', models.FloatField()),
                ('gas_beginning', models.FloatField()),
                ('gasoline_received', models.FloatField()),
                ('gas_received', models.FloatField()),
                ('electronic_gasoline_sales', models.FloatField()),
                ('electronic_gas_sales', models.FloatField()),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField()),
                ('controller', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gasoline', 'Gasoline'), ('gas', 'Gas')], max_length=50)),
                ('start_totalizer', models.FloatField()),
                ('end_totalizer', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.fuelstation')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('gasoline', 'Gasoline'), ('gas', 'Gas')], max_length=50)),
                ('amount', models.FloatField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.fuelstation')),
            ],
        ),
    ]
