# Generated by Django 5.0.6 on 2024-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='end_date',
            field=models.TextField(max_length='30'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='start_date',
            field=models.TextField(max_length='30'),
        ),
    ]
