# Generated by Django 5.0.6 on 2024-07-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_fuelstation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
