# Generated by Django 5.0.6 on 2024-07-10 22:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_fuelstation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
