# Generated by Django 5.0.6 on 2024-07-01 23:15

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_rename_no_gas_nozzles_fuelstation_gas_nozzles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='controller',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='end_date',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='start_date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
