# Generated by Django 5.0.6 on 2024-07-10 22:11

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_fuelstation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
